# Site settings
title: Bart's Blog
email: bart.szulc.qa@gmail.com
description: Bart's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://bart.qa" # the base hostname & protocol for your site
twitter_username: bart.szulc.qa
github_username: bartszulc-qa

# Build settings
markdown: kramdown
highlighter: pygments
